name: Build Qualcomm AX

on: workflow_dispatch

jobs:
    build:
        name: Build Qualcomm AX firmware images
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Install packages
              run: |
                  sudo apt-get update && \
                  sudo apt-get install -y \
                      build-essential \
                      clang \
                      flex \
                      bison \
                      g++ \
                      gawk \
                      gcc-multilib \
                      g++-multilib \
                      gettext \
                      git \
                      libncurses-dev \
                      libssl-dev \
                      python3-distutils \
                      rsync \
                      unzip \
                      zlib1g-dev \
                      file \
                      wget && \
                  sudo apt-get clean

            - name: Checkout
              uses: actions/checkout@v4

            - name: Import config
              run: mv .config_qualcommax .config

            - name: Update feeds
              run: make package/symlinks

            - name: Build firmware images
              id: build1
              continue-on-error: true
              run: make -j$(nproc)

            - name: Build firmware images (V=sc)
              id: build2
              continue-on-error: true
              if: steps.build1.outcome == 'failure'
              run: make -j$(nproc) V=sc

            - name: Build firmware images (-j1)
              id: build3
              continue-on-error: true
              if: steps.build2.outcome == 'failure'
              run: make -j1

            - name: Build firmware images (-j1 V=sc)
              if: steps.build3.outcome == 'failure'
              run: make -j1 V=sc

            - name: Get SHA
              uses: benjlevesque/short-sha@v2.2

            - name: Release
              uses: ncipollo/release-action@v1
              with:
                tag: qualcommax-${{ env.SHA }}
                artifacts: bin/targets/qualcommax/ipq807x/openwrt-qualcommax-ipq807x-*
